using ClashofClans.Files.CsvHelpers;
using ClashofClans.Files.CsvReader;

namespace ClashofClans.Files.Logic
{
	public class LogicCharacterData : LogicData
	{
		public LogicCharacterData(Row row, DataTable datatable) : base(row, datatable)
		{
			LoadData(this, GetType(), row);
		}

		public string Name { get; protected set; }
		public int[] TroopLevel { get; protected set; }
		public bool Deprecated { get; protected set; }
		public string TID { get; protected set; }
		public string InfoTID { get; protected set; }
		public int HousingSpace { get; protected set; }
		public int BarrackLevel { get; protected set; }
		public int[] LaboratoryLevel { get; protected set; }
		public int Speed { get; protected set; }
		public int[] Hitpoints { get; protected set; }
		public int[] TrainingTime { get; protected set; }
		public string TrainingResource { get; protected set; }
		public int[] TrainingCost { get; protected set; }
		public int[] UpgradeTimeH { get; protected set; }
		public int[] UpgradeTimeM { get; protected set; }
		public string UpgradeResource { get; protected set; }
		public int[] UpgradeCost { get; protected set; }
		public int DonateCost { get; protected set; }
		public int DonateXP { get; protected set; }
		public int DonateCount { get; protected set; }
		public int AttackRange { get; protected set; }
		public int[] AttackSpeed { get; protected set; }
		public int CoolDownOverride { get; protected set; }
		public int[] DPS { get; protected set; }
		public int PreferedTargetDamageMod { get; protected set; }
		public int[] DamageRadius { get; protected set; }
		public bool AreaDamageIgnoresWalls { get; protected set; }
		public bool SelfAsAoeCenter { get; protected set; }
		public string IconSWF { get; protected set; }
		public string IconExportName { get; protected set; }
		public string BigPicture { get; protected set; }
		public string BigPictureSWF { get; protected set; }
		public string[] Projectile { get; protected set; }
		public string[] AltProjectile { get; protected set; }
		public string PreferedTargetBuilding { get; protected set; }
		public string PreferedTargetBuildingClass { get; protected set; }
		public bool PreferredTargetNoTargeting { get; protected set; }
		public string DeployEffect { get; protected set; }
		public string[] AttackEffect { get; protected set; }
		public string AttackEffect2 { get; protected set; }
		public string[] HitEffect { get; protected set; }
		public string[] HitEffect2 { get; protected set; }
		public bool IsFlying { get; protected set; }
		public bool AirTargets { get; protected set; }
		public bool GroundTargets { get; protected set; }
		public int[] AttackCount { get; protected set; }
		public string[] DieEffect { get; protected set; }
		public string DieEffect2 { get; protected set; }
		public string[] Animation { get; protected set; }
		public string ProductionBuilding { get; protected set; }
		public bool IsJumper { get; protected set; }
		public int MovementOffsetAmount { get; protected set; }
		public int MovementOffsetSpeed { get; protected set; }
		public string TombStone { get; protected set; }
		public int[] DieDamage { get; protected set; }
		public int DieDamageRadius { get; protected set; }
		public string[] DieDamageEffect { get; protected set; }
		public int DieDamageDelay { get; protected set; }
		public bool DisableProduction { get; protected set; }
		public string[] SecondaryTroop { get; protected set; }
		public bool IsSecondaryTroop { get; protected set; }
		public int[] SecondaryTroopCnt { get; protected set; }
		public int[] SecondarySpawnDist { get; protected set; }
		public bool[] RandomizeSecSpawnDist { get; protected set; }
		public bool PickNewTargetAfterPushback { get; protected set; }
		public int PushbackSpeed { get; protected set; }
		public string SummonTroop { get; protected set; }
		public int[] SummonTroopCount { get; protected set; }
		public int[] SummonCooldown { get; protected set; }
		public string SummonEffect { get; protected set; }
		public int[] SummonLimit { get; protected set; }
		public int SpawnIdle { get; protected set; }
		public bool SpawnOnAttack { get; protected set; }
		public int[] StrengthWeight { get; protected set; }
		public string ChildTroop { get; protected set; }
		public int ChildTroopCount { get; protected set; }
		public int SpeedDecreasePerChildTroopLost { get; protected set; }
		public int ChildTroop0_X { get; protected set; }
		public int ChildTroop0_Y { get; protected set; }
		public int ChildTroop1_X { get; protected set; }
		public int WallMovementCost { get; protected set; }
		public int BurstCount { get; protected set; }
		public int BurstDelay { get; protected set; }
		public bool AttackMultipleBuildings { get; protected set; }
		public bool IncreasingDamage { get; protected set; }
		public int[] DPSLv2 { get; protected set; }
		public int[] DPSLv3 { get; protected set; }
		public int Lv2SwitchTime { get; protected set; }
		public int Lv3SwitchTime { get; protected set; }
		public string AttackEffectLv2 { get; protected set; }
		public string AttackEffectLv3 { get; protected set; }
		public string AttackEffectLv4 { get; protected set; }
		public string TransitionEffectLv2 { get; protected set; }
		public string TransitionEffectLv3 { get; protected set; }
		public string TransitionEffectLv4 { get; protected set; }
		public int TargetedEffectOffset { get; protected set; }
		public int SecondarySpawnOffset { get; protected set; }
		public string CustomDefenderIcon { get; protected set; }
		public int SpecialMovementMod { get; protected set; }
		public int InvisibilityRadius { get; protected set; }
		public int HealthReductionPerSecond { get; protected set; }
		public int AutoMergeDistance { get; protected set; }
		public int AutoMergeGroupSize { get; protected set; }
		public bool IsUnderground { get; protected set; }
		public int ProjectileBounces { get; protected set; }
		public int FriendlyGroupWeight { get; protected set; }
		public int EnemyGroupWeight { get; protected set; }
		public int NewTargetAttackDelay { get; protected set; }
		public bool TriggersTraps { get; protected set; }
		public int ChainShootingDistance { get; protected set; }
		public int ChainAttackDistance { get; protected set; }
		public int ChainAttackMaxTargets { get; protected set; }
		public int ChainAttackDelay { get; protected set; }
		public int ChainAttackDamageReductionPercent { get; protected set; }
		public string ChainAttackEffect { get; protected set; }
		public string PreAttackEffect { get; protected set; }
		public string MoveStartsEffect { get; protected set; }
		public string MoveTrailEffect { get; protected set; }
		public string BecomesTargetableEffect { get; protected set; }
		public bool BoostedIfAlone { get; protected set; }
		public int BoostRadius { get; protected set; }
		public int BoostDmgPerfect { get; protected set; }
		public int BoostAttackSpeed { get; protected set; }
		public string HideEffect { get; protected set; }
		public int VillageType { get; protected set; }
		public int[] UnitsInCamp { get; protected set; }
		public int[] SpecialAbilityLevel { get; protected set; }
		public string SpecialAbilityName { get; protected set; }
		public string SpecialAbilityInfo { get; protected set; }
		public string SpecialAbilityType { get; protected set; }
		public int[] SpecialAbilityAttribute { get; protected set; }
		public int[] SpecialAbilityAttribute2 { get; protected set; }
		public int[] SpecialAbilityAttribute3 { get; protected set; }
		public string SpecialAbilitySpell { get; protected set; }
		public string[] SpecialAbilityEffect { get; protected set; }
		public string SpecialAbilityIcon { get; protected set; }
		public bool DisableDonate { get; protected set; }
		public bool ScaleByTH { get; protected set; }
		public bool EnabledByCalendar { get; protected set; }
		public bool EnabledBySuperLicence { get; protected set; }
		public int LoseHpPerTick { get; protected set; }
		public int LoseHpInterval { get; protected set; }
		public int[] UpgradeLevelByTH { get; protected set; }
		public string EvolveToCharacter { get; protected set; }
		public string EvolveEffect { get; protected set; }
		public int EvolveOnDamageDealt { get; protected set; }
		public int EvolveTime { get; protected set; }
		public bool CanAttackWhileMoving { get; protected set; }
		public string PreferredMovementTarget { get; protected set; }
		public bool RetargetAfterHit { get; protected set; }
		public int[] Damage2 { get; protected set; }
		public int Damage2Radius { get; protected set; }
		public int Damage2Delay { get; protected set; }
		public int[] Damage2Min { get; protected set; }
		public int Damage2FalloffStart { get; protected set; }
		public int Damage2FalloffEnd { get; protected set; }
		public string DamageMultiplierTarget { get; protected set; }
		public int DamageMultiplierPercent { get; protected set; }
		public int FrostOnHitTime { get; protected set; }
		public int FrostOnHitPercent { get; protected set; }
		public bool DoesNotOpenCC { get; protected set; }
		public string DefensiveTroop { get; protected set; }
		public int DamageReductionToStorages { get; protected set; }
		public string[] BunkerTroops { get; protected set; }
		public int[] BunkerTroopCount1 { get; protected set; }
		public int[] BunkerTroopCount2 { get; protected set; }
		public int BunkerDegenerationTime { get; protected set; }
		public int BunkerSpawnDist { get; protected set; }
		public int[] HeroDamageMultiplier { get; protected set; }
		public bool PenetratingProjectile { get; protected set; }
		public int PenetratingRadius { get; protected set; }
		public int PenetratingExtraRange { get; protected set; }
		public bool ImmuneToHealing { get; protected set; }
		public bool PreferHeroes { get; protected set; }
	}
}
